const range=document.getElementById('ageRange');
const output=document.getElementById('ageOutput');
const chart=document.getElementById('chart');
const values=document.getElementById('yearValues');
const title=document.getElementById('chartTitle');
const delta=document.getElementById('delta');
const desc=document.getElementById('chartDesc');
const years=[2026,2027,2028,2029,2030];
const fmt=n=>new Intl.NumberFormat('id-ID',{minimumFractionDigits:6,maximumFractionDigits:6}).format(n);
const ns='http://www.w3.org/2000/svg';
function svg(tag,attributes,text){const el=document.createElementNS(ns,tag);for(const [key,value] of Object.entries(attributes))el.setAttribute(key,value);if(text!==undefined)el.textContent=text;chart.append(el);return el}
function render(data){const age=Number(range.value);const series=years.map(y=>data[String(y)][age]);output.textContent=age+' tahun';title.textContent='Umur '+age+' tahun';const change=(series[4]-series[0])*100;delta.textContent=(change>0?'+':'')+new Intl.NumberFormat('id-ID',{maximumFractionDigits:3}).format(change)+' poin persentase · 2026–2030';desc.textContent='Nilai ramalan XGBoost untuk umur '+age+' tahun: '+years.map((y,i)=>y+' '+fmt(series[i])).join(', ')+'.';values.replaceChildren(...years.map((y,i)=>{const el=document.createElement('div');const label=document.createElement('span');label.textContent=y;const value=document.createElement('strong');value.textContent=fmt(series[i]);el.append(label,value);return el}));document.querySelectorAll('[data-age]').forEach(b=>b.classList.toggle('active',Number(b.dataset.age)===age));chart.replaceChildren(desc);const low=Math.min(...series),high=Math.max(...series),pad=Math.max((high-low)*.28,high*.006,0.000005);const min=Math.max(0,low-pad),max=high+pad;const X=i=>65+i*170,Y=v=>295-(v-min)/(max-min)*235;for(let i=0;i<3;i++){const y=65+i*115;svg('line',{x1:65,y1:y,x2:745,y2:y,stroke:'#ffffff25','stroke-width':1});svg('text',{x:4,y:y+4,fill:'#9db5ba','font-size':13},fmt(max-(y-60)/235*(max-min)))}const points=series.map((v,i)=>`${X(i)},${Y(v)}`).join(' ');svg('polyline',{points,fill:'none',stroke:'#74d9c2','stroke-width':4,'stroke-linejoin':'round','stroke-linecap':'round'});series.forEach((v,i)=>{svg('circle',{cx:X(i),cy:Y(v),r:6,fill:'#eac37a',stroke:'#142e39','stroke-width':3});svg('text',{x:X(i),y:332,fill:'#bcd0d2','font-size':14,'text-anchor':'middle'},String(years[i]))})}
fetch('forecast.json').then(r=>{if(!r.ok)throw Error('data');return r.json()}).then(data=>{range.addEventListener('input',()=>render(data));document.querySelectorAll('[data-age]').forEach(b=>b.addEventListener('click',()=>{range.value=b.dataset.age;render(data)}));render(data)}).catch(()=>{values.textContent='Data ramalan belum dapat dimuat. Muat ulang halaman untuk mencoba lagi.';chart.hidden=true;range.disabled=true});
const progress=document.getElementById('progressFill');function updateProgress(){const total=document.documentElement.scrollHeight-innerHeight;progress.style.width=(total>0?Math.min(100,scrollY/total*100):0)+'%'}addEventListener('scroll',updateProgress,{passive:true});addEventListener('resize',updateProgress);updateProgress();
